### ISSUE TITLE
Implement ports options: STANDARD, MINDSDB

### ISSUE THREAD

**Issue by federico-razzoli** [Vettabase/vagrant-mindsdb#26]
We use these options to configure guest/host port mapping:

```
ports:
  mysql: 47335
  http: 47334
  mongodb: 47336
```

Implement these special values:

- STANDARD (MySQL: 3306, HTTP: 80, MongoDB: 27017)
- MINDSDB (MySQL: 47335, HTTP: 47334, MongoDB: 47336)
